defaults: &defaults
  working_directory: ~/powerRangers
  docker:
    - image: circleci/node:8

version: 2

jobs:
  pre-build:
    <<: *defaults
    steps:
      - checkout:
          path: ~/powerRangers/
      - attach_workspace:
          at: ~/powerRangers/
      - restore_cache:
          key: node-v2-{{ checksum "package.json" }}-{{ arch }}
      - run:
          name: Install modules
          command: npm install
      - save_cache:
          key: node-v2-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/powerRangers
          paths:
            - node_modules
  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/powerRangers
      - run: npm run lint

  gatsby-deploy:
    <<: *defaults
    steps:
      - checkout:
          path: ~/powerRangers/
      - attach_workspace:
          at: ~/powerRangers
      - run:
          name: Install awscli
          command: sudo apt-get -y -qq install awscli
      - run:
          name: Build website
          command: CI=false npm run build:ci
      - run:
          name: Deploy website
          command: aws s3 sync public/ s3://power-rangersiblog  --region eu-west-1 --delete

workflows:
  version: 2
  power-rangers:
    jobs:
      - pre-build:
      - lint:
          requires:
            - pre-build
      - gatsby-deploy:
          requires:
            - lint
          filters:
            branches:
              only:
                - circle-integration
